version: 0.2

phases:
  pre_build:
    commands:
      - aws s3 rm s3://simple-website-pipeline-demo-2142/ --recursive
  build:
    commands:
      - aws s3 cp . s3://simple-website-pipeline-demo-2142/ --recursive
